.gitignore
server/lib/game-mode.js
server/lib/repository.js
server/models/auction.js
server/models/game.js
server/models/player.js
server/models/stats.js
server/repositories/game.js
server/repositories/index.js
server/repositories/player.js
test/lib/repository.test.js
test/mocks/index.js
test/mocks/repo.js
test/models/auction.test.js
test/models/game.test.js
test/models/player.test.js
test/models/stats.test.js

This does not include functionality tied to sockets

Add most of the game functionality

---

server/socket/actions/submit-bid.js
server/socket/actions/update-stats.js
server/socket/events.js
test/server/socket/actions/submit-bid.test.js
test/server/socket/actions/update-stats.test.js

- Adds player event to submit bid
- Adds player event to change goal / skills

Player events

---

server/models/auction.js
server/models/game.js
server/models/player.js
server/socket/actions/join-game.js
server/socket/events.js
test/server/models/auction.test.js
test/server/models/game.test.js
test/server/socket/actions/join-game.test.js
test/server/stubs/create-socket.js

- Adds events for handling auction winners
- Adds events for joining game

Misc events

---

client/components/game/player.js
client/components/game/willpower.js
client/reducers/game.js
client/routes/game/gm-panel.js
client/socket/actions/update-player.js
server/models/game.js
test/client/components/game/player.test.js
test/client/components/game/willpower.test.js
test/client/routes/game/gm-panel.test.js

- Renders all player info on the GM panel
- Adds ability to give / subtract willpower (for GM)

Some GM client functionality

---

client/apps/game.js
client/components/game/bidding.js
client/components/game/player-info.js
client/components/game/player-info.scss
client/components/gm/player.js
client/components/gm/player.scss
client/reducers/types.js
client/sass/global.scss
server/models/game.js
server/models/player.js
server/models/stats.js
test/client/components/game/bidding.test.js
test/client/components/game/player-info.test.js
test/server/models/game.test.js
test/server/models/stats.test.js

- Add ability to bid
- Update game class to handle winner
- Emit winner to clients

Bidding widget

---

client/components/app.js
client/components/error.js
client/components/error.scss
client/constants/error-map.js
client/reducers/app.js
client/reducers/index.js
client/reducers/types.js
client/socket/actions/game-error.js
client/socket/events.js
server/models/player.js
server/socket/actions/join-gm.js
test/client/reducers/app.test.js
test/client/socket/actions/game-error.test.js
test/server/socket/actions/join-game.test.js
test/server/socket/actions/join-gm.test.js

https://jira.kolya.cloud/browse/EIJ-10
- Adds handlers for game rejections
- Right now this is just game.doesntExist

[EIJ-10] Rejection events

---

client/app.js
client/components/app.js
client/components/error.js
client/constants/error-map.js
client/reducers/types.js
client/sass/global.scss
client/utils/error-trap.js

https://jira.kolya.cloud/browse/EIJ-9
- Adds a global error trap to handle exceptions and allow for easy reconnect

[EIJ-9] Global error trap

---

client/routes/game/gm-panel.js
webpack/webpack.common.js

https://jira.kolya.cloud/browse/EIJ-13
Resolves an issue where the GM panel game link would copy incorrectly

[EIJ-13] Fix GM panel link 

---

client/routes/rules.js
client/routes/rules.scss

https://jira.kolya.cloud/browse/EIJ-14
- Adds the rules route

[EIJ-14] Add rules route

---

client/components/header.js
client/components/header.scss
client/routes/game/gm-panel.js
client/routes/game/index.js
client/routes/rules.js
package.json
test/client/components/header.test.js
test/client/routes/game/game.test.js
test/client/routes/game/gm-panel.test.js
test/client/routes/rules.test.js

https://jira.kolya.cloud/browse/EIJ-21
- Adds a `Header` component rendered on all pages but `Home`

[EIJ-21] Add header bar

---

client/components/game/goal.js
client/components/game/name.js
client/components/game/skill-list.js
client/constants/sockets.js
package-lock.json
package.json
test/client/components/game/goal.test.js
test/client/components/game/name.test.js
test/client/components/game/skill-list.test.js

- Removes submit buttons from game panel
- Debounce change events to emit obsessions

[EIJ-12] Remove Submit buttons

---

client/constants/error-map.js
client/socket/actions/disconnect.js
client/socket/events.js
test/client/socket/actions/disconnect.test.js

https://jira.kolya.cloud/browse/EIJ-27
- Emits an `app.socketDisconnect` error if the socket connections drops.

[EIJ-27] Emit error if socket gets disconnected

---

server/socket/actions/disconnect.js

https://jira.kolya.cloud/browse/EIJ-24
- Fixes a bug where a player not in a game would not disconnect

[EIJ-24] Ensure players not in games disconnect properly

---

client/components/join-input.js
test/client/components/join-input.test.js

https://jira.kolya.cloud/browse/EIJ-28
- Makes the enter key submit the join form on the home page

[EIJ-28] Enter button joins game

---

client/routes/rules.scss

- Reduces header size for rules page on mobile to fit in viewport

[EIJ-32] Fix rules header size

---

.circleci/config.yml

EIJ alpha-1.0

---

client/components/game/goal.js
client/components/game/player-info.js
client/components/game/skill-list.js
client/components/gm/goal.js
client/components/gm/player.js
client/components/gm/skill-list.js
client/store.js
package-lock.json
package.json
server/models/player.js
server/models/stats.js
server/socket/actions/reject-goal.js
server/socket/actions/reject-skill.js
server/socket/events.js
test/client/components/game/goal.test.js
test/client/components/game/player-info.test.js
test/client/components/game/skill-list.test.js
test/client/components/gm/goal.test.js
test/client/components/gm/player.test.js
test/client/components/gm/skill-list.test.js
test/server/models/stats.test.js
test/server/socket/actions/reject-goal.test.js
test/server/socket/actions/reject-skill.test.js

https://jira.kolya.cloud/browse/EIJ-26
Functionality to allow GM to reject skills / obsessions

[EIJ-26] Reject skills / obsessions

---

client/store.js

https://jira.kolya.cloud/browse/EIJ-40
Refactors the middlewares to fix a bug where returning undefined from the `logger` method in the redux store was causing a broken deployment

[EIJ-40] Fix e is not a function bug in deployment

---

client/components/gm/kick.js
client/components/gm/player.js
client/constants/error-map.js
client/socket/actions/game-kick.js
client/socket/events.js
server/models/game.js
server/socket/actions/kick-player.js
server/socket/events.js
test/client/components/gm/kick.test.js
test/client/components/gm/player.test.js
test/client/socket/actions/game-kick.test.js
test/server/models/game.test.js
test/server/socket/actions/kick-player.test.js

https://jira.kolya.cloud/browse/EIJ-30
- Add ability for GM to kick players

[EIJ-30] Allow players to be kicked

---

client/components/game/player-info.js
client/components/gm/game-controls.js
client/components/gm/ticker.js
client/constants/game.js
package-lock.json
package.json
test/client/components/gm/game-controls.test.js
test/client/components/gm/ticker.test.js

https://jira.kolya.cloud/browse/EIJ-39
- Adds functionality to allow GM to subtract / add willpower to all players at once
- Migrates client side game modes to constants

[EIJ-39] Allow GM to add / subtract willpower from everyone

---

server/socket/actions/disconnect.js
test/server/socket/actions/disconnect.test.js

https://jira.kolya.cloud/browse/EIJ-44
- Prevents a server hard-crash if a socket disconnects that (somehow) does not have a player bound to it

[EIJ-44] Prevent crash for null player

---

server/models/game.js
server/models/player.js
test/server/models/game.test.js
test/server/models/player.test.js

https://jira.kolya.cloud/browse/EIJ-43
- Fixes an issue where a player moving from one game to a new one would see the "You were removed from the game" screen

[EIJ-43] Prevent "You were removed" screen upon switching games

---

client/components/gm/game-controls.scss
client/components/header.scss

https://jira.kolya.cloud/browse/EIJ-31
- Indents the Game Controls by 0.5em
- Adds a hover effect to the header link to increase discoverability

[EIJ-31] Increase header button visibility

---

client/app.js
client/route-controller.js
package-lock.json
package.json
test/client/app.test.js
test/client/route-controller.test.js

- Extract route controller into its own component and add some top level tests

Clean up route controller

---

server/models/game.js
test/server/models/game.test.js

https://jira.kolya.cloud/browse/EIJ-54
- Fixes an issue where the game mode was not emitted to the GM

[EIJ-54] Fix issue where GM would not receive game mode

---

client/components/game/player-info.js
client/components/game/section.scss
client/components/game/skill-list.js
client/components/gm/player.js
client/reducers/game.js
client/reducers/player.js
client/reducers/types.js
client/socket/actions/set-skills.js
client/socket/events.js
package-lock.json
package.json
server/models/player.js
server/models/stats.js
server/socket/actions/update-stats.js
test/client/components/game/player-info.test.js
test/client/components/game/skill-list.test.js
test/client/components/gm/player.test.js
test/client/reducers/game.test.js
test/client/reducers/player.test.js
test/client/socket/actions/set-skills.test.js
test/server/models/player.test.js
test/server/models/stats.test.js
test/server/socket/actions/reject-skill.test.js
test/server/socket/actions/update-stats.test.js

https://jira.kolya.cloud/browse/EIJ-11
- Refactors skills to use arrays instead of being separate keys
- Subsequently fixes issues that were the reason for using separate keys
- Fixes issue where entering skills too fast would result in deletion
- Fixes issue where skills could not be properly deleted
- Adds a warning / prompt before the user adds a 3rd skill
- Make sure they know that it costs 3 willpower

[EIJ-11] Warning for 3rd skill

---

client/actions/set-connection-status.js
client/components/header.js
client/components/spinner.js
client/components/spinner.scss
client/constants/connection-status.js
client/constants/settings.js
client/reducers/app.js
client/reducers/types.js
client/socket/actions/disconnect.js
client/socket/actions/reconnect-failed.js
client/socket/client.js
client/socket/events.js
test/client/actions/set-connection-status.test.js
test/client/components/header.test.js
test/client/components/spinner.test.js
test/client/reducers/app.test.js
test/client/routes/game/game.test.js
test/client/routes/game/gm-panel.test.js
test/client/routes/rules.test.js
test/client/socket/actions/disconnect.test.js
test/client/socket/actions/reconnect-failed.test.js
test/client/socket/client.test.js

https://jira.kolya.cloud/browse/EIJ-60
- Track connection status
- Retry connections up to 10 times
- Add a visual spinner

[EIJ-60] Retry connections

---

client/reducers/game.js
client/socket/actions/chat-receive.js
client/socket/events.js
server/models/chat.js
server/models/game.js
server/models/message.js
server/socket/actions/send-message.js
server/socket/events.js
test/client/reducers/game.test.js
test/client/socket/actions/chat-receive.test.js
test/server/models/chat.test.js
test/server/models/game.test.js
test/server/models/message.test.js
test/server/socket/actions/send-message.test.js
test/server/stubs/create-socket.js

https://jira.kolya.cloud/browse/EIJ-18
- Adds `Chat` + `Message` classes
- Adds ability to send messages between owner / player clients
- Store messages in redux store

[EIJ-18] Chat classes

---

.npmrc
client/components/game/skill-list.js
client/components/gm/ticker.js
client/components/reject.js
client/components/sound-control.js
client/components/spinner.js
package-lock.json
package.json
test/client/components/reject.test.js
test/client/components/sound-control.test.js
test/client/components/spinner.test.js

- Upgraded express-to-koa to 1.2.0
- Uses fontawesome free icons, so that anyone can install and run

Fix build issues
